FROM debian:latest

RUN apt-get update
RUN apt-get install --allow-unauthenticated dirmngr
RUN echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee /etc/apt/sources.list.d/webupd8team-java.list
RUN echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
RUN apt-get update
RUN apt-get --allow-unauthenticated install oracle-java8-installer
RUN apt-get --allow-unauthenticated install oracle-java8-set-default